# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_stabilizer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16video_stabilizer.proto\x12\x05unary\"a\n\x10StabilizeRequest\x12\x13\n\x0b\x66rame_image\x18\x01 \x01(\x0c\x12\x12\n\nprev_frame\x18\x02 \x01(\x0c\x12\x0f\n\x07padding\x18\x03 \x01(\x05\x12\x13\n\x0b\x66rame_index\x18\x04 \x01(\x05\"3\n\x11StabilizeResponse\x12\x1e\n\x16stabilized_frame_image\x18\x01 \x01(\x0c\"6\n\x0b\x46lowRequest\x12\x12\n\nprev_frame\x18\x01 \x01(\x0c\x12\x13\n\x0b\x66rame_image\x18\x02 \x01(\x0c\"\x0e\n\x0c\x46lowResponse\"\x0f\n\rCumSumRequest\"\x10\n\x0e\x43umSumResponse2S\n\x0fVideoStabilizer\x12@\n\tStabilize\x12\x17.unary.StabilizeRequest\x1a\x18.unary.StabilizeResponse\"\x00\x32\x39\n\x04\x46low\x12\x31\n\x04\x46low\x12\x12.unary.FlowRequest\x1a\x13.unary.FlowResponse\"\x00\x32\x41\n\x06\x43umSum\x12\x37\n\x06\x43umSum\x12\x14.unary.CumSumRequest\x1a\x15.unary.CumSumResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stabilizer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STABILIZEREQUEST._serialized_start=33
  _STABILIZEREQUEST._serialized_end=130
  _STABILIZERESPONSE._serialized_start=132
  _STABILIZERESPONSE._serialized_end=183
  _FLOWREQUEST._serialized_start=185
  _FLOWREQUEST._serialized_end=239
  _FLOWRESPONSE._serialized_start=241
  _FLOWRESPONSE._serialized_end=255
  _CUMSUMREQUEST._serialized_start=257
  _CUMSUMREQUEST._serialized_end=272
  _CUMSUMRESPONSE._serialized_start=274
  _CUMSUMRESPONSE._serialized_end=290
  _VIDEOSTABILIZER._serialized_start=292
  _VIDEOSTABILIZER._serialized_end=375
  _FLOW._serialized_start=377
  _FLOW._serialized_end=434
  _CUMSUM._serialized_start=436
  _CUMSUM._serialized_end=501
# @@protoc_insertion_point(module_scope)
